PMMI Side of Inquiry Form Update
parameter1/pmmi-media-group-websites pull request #211
Opened 2021-05-20 21:19 UTC by Shinsina

<img width="1920" alt="Screen Shot 2021-05-20 at 4 11 31 PM" src="https://user-images.githubusercontent.com/46794001/119050112-0628e900-b987-11eb-8a30-c8b5c51db288.png">
<img width="1920" alt="Screen Shot 2021-05-20 at 4 18 51 PM" src="https://user-images.githubusercontent.com/46794001/119050166-16d95f00-b987-11eb-8396-82c489cb4583.png">

2021-05-20 21:21 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [How to solve for Mundo Leaders entries in Spanish and English](https://trello.com/c/oKzezqPm/50-how-to-solve-for-mundo-leaders-entries-in-spanish-and-english)

2021-05-26 15:28 UTC, solocommand requested changes

2021-05-26 15:28 UTC, solocommand commented on packages/shared/templates/content/company.marko
> +$ const lang = input.lang
Missing semicolon

2021-05-26 15:28 UTC, solocommand commented on packages/shared/components/page-wrappers/content/leader.marko
> +$ const lang = site.config.lang || 'en'
Use double quotes in template files

2021-05-26 19:07 UTC, solocommand requested changes

2021-05-26 19:07 UTC, solocommand commented on packages/shared/components/page-wrappers/content/leader.marko
> +$ const lang = site.config.lang || "en"
Missing semicolon

2021-05-26 21:22 UTC, solocommand approved these changes

2021-05-26 21:22 UTC, merged