Change to other areas of the leaders page mundo
parameter1/pmmi-media-group-websites pull request #212
Opened 2021-05-21 13:36 UTC by Shinsina

Ths replaces PR #210

2021-05-21 14:16 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [How to solve for Mundo Leaders entries in Spanish and English](https://trello.com/c/oKzezqPm/50-how-to-solve-for-mundo-leaders-entries-in-spanish-and-english)

2021-05-21 14:26 UTC, Shinsina commented
<img width="1920" alt="Screen Shot 2021-05-21 at 9 22 53 AM" src="https://user-images.githubusercontent.com/46794001/119153214-a9750f00-ba16-11eb-8c72-fa4868952689.png">
<img width="1920" alt="Screen Shot 2021-05-21 at 9 10 50 AM" src="https://user-images.githubusercontent.com/46794001/119153229-ad089600-ba16-11eb-9a70-cce39b65b15c.png">

2021-05-26 15:25 UTC, solocommand requested changes

2021-05-26 15:25 UTC, solocommand commented on packages/common/components/blocks/company-details.marko
> +$ const lang = input.lang || 'en'
Use double quotes in template files (bonus points for fixing the definitions above too)

2021-05-26 18:38 UTC, solocommand requested changes

2021-05-26 18:38 UTC, solocommand commented on packages/shared/components/page-wrappers/content/leader.marko
> +$ const lang = site.config.lang || "en"
Where possible you should avoid accessing deeply nested properties and use a utility to retrieve them. Preferably this should be written as one of the following:
```js
import { defaultValue } from "@parameter1/base-cms-marko-web/utils";
$ const lang = defaultValue(site, "config.lang", "en");
```
or
```js
import { getAsObject } from "@parameter1/base-cms-object-path";
$ const { lang = "en" } = getAsObject(site, "config");
```

2021-05-27 15:21 UTC, merged