Update Podcast Page Template and routing Automation World Global (Monorail) site.
parameter1/pmmi-media-group-websites pull request #368
Opened 2022-06-20 19:03 UTC by Shinsina

Hero block only displays  on the first page of results

![Podcasts](https://user-images.githubusercontent.com/46794001/174664115-1aa05887-4722-430f-b687-45ce4cb8a0bc.png)

NOTE: Items will need to be scheduled to the new AW Podcasts section in order for this page to work.

2022-06-20 19:06 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Subsection for AW Podcasts](https://trello.com/c/HYZwLgVX/356-subsection-for-aw-podcasts)

2022-06-20 23:40 UTC, brandonbk requested changes

2022-06-20 23:40 UTC, brandonbk commented on packages/global/start-server.js
> +  sharedRoutes(app, siteConfig);
@Shinsina - on one hand, I can see why you changed the order.  If the site routes run first, it allows for a custom /podcast route (and therefore template) to override the global version.  Makes sense...except that this customer is now different than everyone else, which we don't want.

So...one of two things needs to happen:
- Discuss as a group and make this the new standard across all customers.  Would likely break a lot of things that expect the reverse order.
- Take the /podcasts route out of the Global package for PMMI and add to each site individually.  All sites except AW can still reference the global template, but AW can reference the custom site one.

#2 is far less invasive and probably the way we should go for now, but I'm open to discussing.

2022-06-21 16:11 UTC, brandonbk approved these changes

2022-06-21 16:11 UTC, merged