Newsletter signup changes
parameter1/pmmi-media-group-websites pull request #383
Opened 2022-07-19 17:08 UTC by jwade1327

AW:
<img width="1278" alt="Screen Shot 2022-07-19 at 11 41 05 AM" src="https://user-images.githubusercontent.com/64623209/179808871-a63321c6-5673-4d4a-b8c4-5789c8231a99.png">
<img width="1293" alt="Screen Shot 2022-07-19 at 11 41 16 AM" src="https://user-images.githubusercontent.com/64623209/179808877-3e003b2f-f653-486e-b831-ad1e60845938.png">
HCP:
<img width="1209" alt="Screen Shot 2022-07-19 at 11 49 04 AM" src="https://user-images.githubusercontent.com/64623209/179808921-4ec75f77-5dfe-4aa2-a74a-19de81c57235.png">
<img width="1228" alt="Screen Shot 2022-07-19 at 11 49 14 AM" src="https://user-images.githubusercontent.com/64623209/179808928-07d5c988-289a-4ad2-9aaa-e758544915b6.png">
OEM:
<img width="1191" alt="Screen Shot 2022-07-19 at 11 57 31 AM" src="https://user-images.githubusercontent.com/64623209/179809062-467c9850-d1bd-48bc-a17d-f723a1fa8b42.png">
<img width="1206" alt="Screen Shot 2022-07-19 at 11 57 37 AM" src="https://user-images.githubusercontent.com/64623209/179809069-237dfe32-7ef1-423a-96b1-435878ef84ac.png">
PW:
<img width="1208" alt="Screen Shot 2022-07-19 at 12 01 18 PM" src="https://user-images.githubusercontent.com/64623209/179809096-177560d6-2248-4526-a796-d7d7060f6bca.png">
<img width="1183" alt="Screen Shot 2022-07-19 at 12 01 24 PM" src="https://user-images.githubusercontent.com/64623209/179809099-cc83c26d-654b-4de8-857b-d30ccc1fa3a9.png">
PFW:
<img width="1266" alt="Screen Shot 2022-07-19 at 12 05 06 PM" src="https://user-images.githubusercontent.com/64623209/179809102-8756a942-3ed7-419a-977a-735ca5270f71.png">
<img width="1239" alt="Screen Shot 2022-07-19 at 12 05 13 PM" src="https://user-images.githubusercontent.com/64623209/179809105-1d7a17b7-b1b5-4edb-acee-e1556d108c55.png">

2022-07-19 17:16 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [PFW: Newsletter Signup Info](https://trello.com/c/g8IIaZ8V/345-pfw-newsletter-signup-info)

2022-07-19 17:17 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [PW: Newsletter Signup Info](https://trello.com/c/cI5jwQDc/344-pw-newsletter-signup-info)

2022-07-19 17:17 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [OEM: Newsletter Signup Info](https://trello.com/c/RLM4VRu9/346-oem-newsletter-signup-info)

2022-07-19 17:17 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [HCP: Newsletter Signup Info](https://trello.com/c/vgksYrC2/347-hcp-newsletter-signup-info)

2022-07-20 17:46 UTC, B77Mills approved these changes

2022-07-20 18:41 UTC, brandonbk requested changes

2022-07-20 18:41 UTC, brandonbk commented on packages/global/components/document.marko
>  $ const continueLable = i18n("Sign Me Up!");
`continueLable` is incorrectly spelled; is it wrong in the low-level component as well?

2022-07-20 18:41 UTC, brandonbk commented on packages/global/components/layouts/content/default.marko
>  $ const continueLable = i18n("Sign Me Up!");
`continueLable` spelled wrong here as well

2022-07-21 12:13 UTC, merged