Use a single column layout and don't load primary images for webinar pages.
parameter1/pmmi-media-group-websites pull request #408
Opened 2022-08-02 17:59 UTC by Shinsina

![webinar-layout-1](https://user-images.githubusercontent.com/46794001/182442551-18c134e5-cbc4-4209-ba7b-5021cc119f48.png)
![webinar-layout-2](https://user-images.githubusercontent.com/46794001/182442554-685878d7-91ee-4ed7-9c87-55a3077c92e7.png)
![webinar-layout-3](https://user-images.githubusercontent.com/46794001/182442555-54829ca9-30c5-4008-8bd1-06ab33cf23e1.png)

2022-08-02 18:00 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Change to Webinar Pages](https://trello.com/c/QWqBTWOm/408-change-to-webinar-pages)

2022-08-02 19:21 UTC, B77Mills requested changes

2022-08-02 19:21 UTC, B77Mills commented on packages/global/components/layouts/content/webinar.marko
> +            <if(leadersContentTypes.includes(content.type))>
This if check can be removed along with the one on line 144.  Please also remove the const on line 9.

2022-08-02 19:21 UTC, B77Mills commented on packages/global/components/layouts/content/webinar.marko
> +  <@section|{ blockName, content, aliases, authors }| modifiers=["content-header"]>
authors can be removed here along with lines 36 - 46.  I webinars do not have an author field.

2022-08-02 19:21 UTC, B77Mills commented on packages/global/components/layouts/content/webinar.marko
> +  <@section|{ aliases, content, authors }| modifiers=["content-body"]>
remove authors from here and line 102 - 106

2022-08-03 14:53 UTC, B77Mills approved these changes

2022-08-03 14:53 UTC, merged