Update newsletterSate middleware configuration & how it is being included
parameter1/pmmi-media-group-websites pull request #432
Opened 2022-08-19 14:46 UTC by B77Mills

Move the inclusion of the newsletterState out of the start server and down into the individual route that need to use it.  Also added configuration logic for excludeGatedContent & excludeContentTypes.

The way they have it configured at the moment it would not trigger on any content that is a page type or is gatedByReg.  It should still fire on all other content, section & home pages.  

Also update it so it only drops the cookie when initiallyExpanded is true.  Meaning it will only drop the cookie if it is telling it to display.  

Gated Piece of content(doesn't display or drop cookie) :
<img width="1462" alt="Screen Shot 2022-08-19 at 9 42 24 AM" src="https://user-images.githubusercontent.com/3845869/185644633-7b80e222-14f1-4e54-988e-989cee3b14a8.png">

Non restricted after that drops the cookie and displays pushdown:
<img width="1555" alt="Screen Shot 2022-08-19 at 9 46 26 AM" src="https://user-images.githubusercontent.com/3845869/185644972-adee9d5d-669f-4e13-b4e3-dc77d02bcf06.png">

2022-08-25 17:28 UTC, B77Mills commented
![](https://github.trello.services/images/mini-trello-icon.png) [Reskin: Suppress NL Enticements on "Page" Content Type](https://trello.com/c/dkySxt5W/418-reskin-suppress-nl-enticements-on-page-content-type)

2022-08-26 14:37 UTC, zarathustra323 requested changes

2022-08-26 14:37 UTC, zarathustra323 commented on packages/global/middleware/newsletter-state.js
> +module.exports = () => asyncRoute(async (req, res, next) => {
`module.exports = ({ setCookie = true } = {}) => (req, res, next) => {`

2022-08-26 14:37 UTC, zarathustra323 commented on packages/global/routes/content.js
> +  app.get('/*?contact/:id(\\d{8})*', newsletterState(), withContent({
`app.get('/*?contact/:id(\\d{8})*', newsletterState({ setCookie: false }), withContent({`

2022-08-26 14:37 UTC, zarathustra323 commented on packages/global/middleware/newsletter-state.js
> +  if (initiallyExpanded) {
`if (setCookie && initiallyExpanded) {`

2022-08-26 14:37 UTC, zarathustra323 commented on packages/global/middleware/newsletter-state.js
>      // Expire in 14 days (2yr if already signed up)
Move:
```js
    // Expire in 14 days (2yr if already signed up)
    const days = fromEmail ? 365 * 2 : 14;
    const maxAge = days * 24 * 60 * 60 * 1000;
```
above the if check

2022-08-26 14:37 UTC, zarathustra323 commented on packages/global/middleware/newsletter-state.js
>    res.locals.newsletterState = { hasCookie, fromEmail, initiallyExpanded };
```js
res.locals.newsletterState = {
  hasCookie,
  fromEmail,
  initiallyExpanded,
  cookie: { name: cookieName, maxAge }
};
```

2022-08-26 14:37 UTC, zarathustra323 commented on packages/global/routes/content.js
Add:
```js
const formatResponse = ({ res, content }) => {
  console.log({ newsletterState: res.locals.newsletterState });

  const { initiallyExpanded, cookie } = res.locals.newsletterState;

  if (content.requiresRegistration === true) {
    res.locals.newsletterState.initiallyExpanded = false;
  } else if (initiallyExpanded) {
    res.cookie(cookie.name, true, { maxAge: cookie.maxAge });
  }
};
```

2022-08-26 14:37 UTC, zarathustra323 commented on packages/global/routes/content.js
> +  app.get('/*?:id(\\d{8})*', newsletterState(), withContent({
Change all routes to be similar to this:
```js
app.get('/*?:id(\\d{8})*', newsletterState({ setCookie: false }), withContent({
  template: content,
  queryFragment: contentQueryFragmentFn(site.get('leaders.alias')),
  formatResponse,
}));
```

2022-08-26 14:37 UTC, zarathustra323 commented on packages/global/middleware/newsletter-state.js
> +const gql = require('graphql-tag');
Now all the query stuff can be removed

2022-09-15 15:33 UTC, merged